---
- hosts: database

  handlers:
    - name: restart_mysql
      service:
        name: mysql
        state: restarted
      become: yes  

  tasks:
    - name: 'Instala pacotes de dependencia do sistema operacional'
      apt:
        name: "{{ item }}"
        state: latest
      become: yes
      with_items:
        - mysql-server-5.6
        - python-mysqldb

    - name: 'Cria o banco Mysql'
      mysql_db:
        name: "{{ wp_db_name }}"
        login_user: root
        state: present

    - name: 'Cria usuario e atribui permissoes ao usuario no {{ wp_db_name }}'
      mysql_user:
        login_user: root
        name: "{{ wp_username }}"
        password: "{{ wp_user_password }}"
        priv: '{{ wp_db_name }}.*:ALL'
        state: present
        host: "{{ item }}"
      with_items:
        - 'localhost'
        - '127.0.0.1'
        - "{{ wp_host_ip }}"

    - name: 'Copiar arquivo my.cnf na maquina que roda o ansible para a maquina virtual do mysql'
      copy:
        src: './files/my.cnf'
        dest: '/etc/mysql/my.cnf'
        remote_src: no
      become: yes
      notify: 
        - restart_mysql      

- hosts: wordpress
  
  handlers:
    - name: restart_apache
      service:
        name: apache2
        state: restarted
      become: yes    

  tasks:
    - name: 'Instala pacotes de dependencia do sistema operacional'
      apt:
        name: "{{ item }}"
        state: latest
      become: yes
      with_items:
        - php5
        - apache2
        - libapache2-mod-php5
        - php5-gd
        - libssh2-php
        - php5-mcrypt
        - php5-mysql

    - name: 'Download baixa o arquivo de instalacao do wordpress'
      get_url:
        url: 'https://wordpress.org/latest.tar.gz'
        dest: '/tmp/wordpress.tar.gz'
    
    - name: 'Descompactar o arquivo de wordpress'
      unarchive:
        src: '/tmp/wordpress.tar.gz'
        dest: '/var/www/'
        remote_src: yes
      become: yes

    - name: 'Criar arquivo wp-config.php a partir de wp-config-sample.php'
      copy:
        src: '{{ wp_installation_path }}/wp-config-sample.php'
        dest: '{{ wp_installation_path }}/wp-config.php'
        remote_src: yes
      become: yes
    
    - name: 'Configurar o wp com as entradas do banco de dados'
      replace:
        path: '{{ wp_installation_path }}/wp-config.php'
        regexp: "{{ item.regex }}"
        replace: "{{ item.value }}"
        backup: yes
      with_items:
        - { regex: 'database_name_here', value: "{{ wp_db_name }}" }
        - { regex: 'username_here', value: "{{ wp_username }}" }
        - { regex: 'password_here', value: "{{ wp_user_password }}" }
        - { regex: 'localhost', value: "{{ wp_db_ip }}" }
      become: yes

    - name: 'Configura Apache para servir'
      template:
        src: 'templates/000-default.conf.j2'
        dest: '/etc/apache2/sites-available/000-default.conf'
      become: yes
      notify: 
        - restart_apache

        
    # - name: 'Copiar arquivo 000-default.conf na maquina que roda o ansible para apache da maquina virtual'
    #   copy:
    #     src: './files/000-default.conf'
    #     dest: '/etc/apache2/sites-available/000-default.conf'
    #     remote_src: no
    #   become: yes
    #   notify: 
    #     - restart_apache
