---
  - name: 'Download baixa o arquivo de instalacao do wordpress'
    get_url:
      url: 'https://wordpress.org/latest.tar.gz'
      dest: '/tmp/wordpress.tar.gz'
  
  - name: 'Descompactar o arquivo de wordpress'
    unarchive:
      src: '/tmp/wordpress.tar.gz'
      dest: '/var/www/'
      remote_src: yes
    become: yes  
  - name: 'Criar arquivo wp-config.php a partir de wp-config-sample.php'
    copy:
      src: '{{ wp_installation_path }}/wp-config-sample.php'
      dest: '{{ wp_installation_path }}/wp-config.php'
      remote_src: yes
    become: yes
  
  - name: 'Configurar o wp com as entradas do banco de dados'
    replace:
      path: '{{ wp_installation_path }}/wp-config.php'
      regexp: "{{ item.regex }}"
      replace: "{{ item.value }}"
      backup: yes
    with_items:
      - { regex: 'database_name_here', value: "{{ wp_db_name }}" }
      - { regex: 'username_here', value: "{{ wp_username }}" }
      - { regex: 'password_here', value: "{{ wp_user_password }}" }
      - { regex: 'localhost', value: "{{ wp_db_ip }}" }
    become: yes

  - name: 'Configura Apache para servir'
    template:
      src: 'templates/000-default.conf.j2'
      dest: '/etc/apache2/sites-available/000-default.conf'
    become: yes
    notify: 
      - restart_apache